# Iris 분류

### Logistic Regression

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
# data, target, target_names, feature_names, DESCR
data = iris.data
label = iris.target
columns = iris.feature_names
df = pd.DataFrame(data, columns=columns)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = \
    train_test_split(data, label, test_size=0.2, 
                     shuffle=True, stratify=label, random_state=2019)

* 모델 객체 생성

In [5]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

* 모델 학습

In [6]:
lr.fit(x_train, y_train)

LogisticRegression()

* 학습한 결과를 저장

In [7]:
import joblib
joblib.dump(lr, 'model/iris_lr.pkl')

['model/iris_lr.pkl']

### Support Vector Machine

In [8]:
from sklearn.svm import SVC

In [9]:
# 모델 객체 생성
svc = SVC()

In [10]:
# 학습
svc.fit(x_train, y_train)

SVC()

In [11]:
import joblib
joblib.dump(lr, 'model/iris_svm.pkl')

['model/iris_svm.pkl']

### Decision Tree

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
dtc = DecisionTreeClassifier()

In [14]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [15]:
import joblib
joblib.dump(lr, 'model/iris_dt.pkl')

['model/iris_dt.pkl']

### 저장된 모델로 정확도 산출

In [16]:
model_lr = joblib.load('model/iris_lr.pkl')
model_svm = joblib.load('model/iris_svm.pkl')
model_dt = joblib.load('model/iris_dt.pkl')

In [17]:
y_pred_lr = model_lr.predict(x_test)
y_pred_svm = model_svm.predict(x_test)
y_pred_dt = model_dt.predict(x_test)

In [18]:
from sklearn.metrics import accuracy_score
acc_lr = accuracy_score(y_test, y_pred_lr)
acc_svm = accuracy_score(y_test, y_pred_svm)
acc_dt = accuracy_score(y_test, y_pred_dt)
print(acc_lr, acc_svm, acc_dt)

0.9666666666666667 0.9666666666666667 0.9666666666666667


### 한개의 테스트 값 예측

In [19]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [20]:
test_data = np.array([6.7, 3.0, 5.2, 2.3]).reshape(1, 4)

In [21]:
index_lr = model_lr.predict(test_data)[0]
index_svm = model_svm.predict(test_data)[0]
index_dt = model_dt.predict(test_data)[0]

In [22]:
sp_names = ['Setosa', 'Versicolor', 'Virginica']
print(sp_names[index_lr], sp_names[index_svm], sp_names[index_dt])

Virginica Virginica Virginica


### Deep learning model

In [32]:
# 딥러닝 모델 설정
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential([
    Dense(12, input_shape=(4,), activation='relu'),
    Dense(8, input_shape=(4,), activation='relu'),
    Dense(3, activation='softmax')
])

In [34]:
# 모델 컴파일
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics = ['accuracy'])

In [39]:
from keras.callbacks import ModelCheckpoint
checkpointer = ModelCheckpoint(filepath = 'model/iris_deep.hdf5',
                            monitor ='val_loss',
                            verbose = 1, save_best_only=True)

In [40]:
#one hot encoding
Y_encoded = keras.utils.to_categorical(y_train)
Y_encoded[0], Y_encoded[50], Y_encoded[100]

(array([1., 0., 0.], dtype=float32),
 array([0., 0., 1.], dtype=float32),
 array([0., 0., 1.], dtype=float32))

In [41]:
# 모델 생성
model.fit(x_train, Y_encoded, epochs=100, batch_size=30, verbose=2,
         validation_split=0.2, callbacks=[checkpointer])

Train on 96 samples, validate on 24 samples
Epoch 1/100
 - 0s - loss: 1.5315 - accuracy: 0.3125 - val_loss: 1.3570 - val_accuracy: 0.4167

Epoch 00001: val_loss improved from inf to 1.35701, saving model to model/iris_deep.hdf5
Epoch 2/100
 - 0s - loss: 1.4637 - accuracy: 0.3125 - val_loss: 1.3220 - val_accuracy: 0.4167

Epoch 00002: val_loss improved from 1.35701 to 1.32198, saving model to model/iris_deep.hdf5
Epoch 3/100
 - 0s - loss: 1.4081 - accuracy: 0.3021 - val_loss: 1.2906 - val_accuracy: 0.2500

Epoch 00003: val_loss improved from 1.32198 to 1.29055, saving model to model/iris_deep.hdf5
Epoch 4/100
 - 0s - loss: 1.3668 - accuracy: 0.2500 - val_loss: 1.2616 - val_accuracy: 0.1250

Epoch 00004: val_loss improved from 1.29055 to 1.26164, saving model to model/iris_deep.hdf5
Epoch 5/100
 - 0s - loss: 1.3185 - accuracy: 0.1458 - val_loss: 1.2352 - val_accuracy: 0.0417

Epoch 00005: val_loss improved from 1.26164 to 1.23519, saving model to model/iris_deep.hdf5
Epoch 6/100
 - 0s - 


Epoch 00044: val_loss improved from 0.49344 to 0.48693, saving model to model/iris_deep.hdf5
Epoch 45/100
 - 0s - loss: 0.4802 - accuracy: 0.8958 - val_loss: 0.4806 - val_accuracy: 0.9167

Epoch 00045: val_loss improved from 0.48693 to 0.48063, saving model to model/iris_deep.hdf5
Epoch 46/100
 - 0s - loss: 0.4742 - accuracy: 0.9375 - val_loss: 0.4746 - val_accuracy: 0.9167

Epoch 00046: val_loss improved from 0.48063 to 0.47460, saving model to model/iris_deep.hdf5
Epoch 47/100
 - 0s - loss: 0.4685 - accuracy: 0.9375 - val_loss: 0.4684 - val_accuracy: 0.9167

Epoch 00047: val_loss improved from 0.47460 to 0.46844, saving model to model/iris_deep.hdf5
Epoch 48/100
 - 0s - loss: 0.4633 - accuracy: 0.9375 - val_loss: 0.4625 - val_accuracy: 0.9167

Epoch 00048: val_loss improved from 0.46844 to 0.46252, saving model to model/iris_deep.hdf5
Epoch 49/100
 - 0s - loss: 0.4581 - accuracy: 0.9479 - val_loss: 0.4574 - val_accuracy: 0.9583

Epoch 00049: val_loss improved from 0.46252 to 0.45736


Epoch 00088: val_loss did not improve from 0.32599
Epoch 89/100
 - 0s - loss: 0.3275 - accuracy: 0.9583 - val_loss: 0.3216 - val_accuracy: 0.9583

Epoch 00089: val_loss improved from 0.32599 to 0.32156, saving model to model/iris_deep.hdf5
Epoch 90/100
 - 0s - loss: 0.3246 - accuracy: 0.9583 - val_loss: 0.3173 - val_accuracy: 0.9583

Epoch 00090: val_loss improved from 0.32156 to 0.31735, saving model to model/iris_deep.hdf5
Epoch 91/100
 - 0s - loss: 0.3220 - accuracy: 0.9583 - val_loss: 0.3131 - val_accuracy: 0.9583

Epoch 00091: val_loss improved from 0.31735 to 0.31307, saving model to model/iris_deep.hdf5
Epoch 92/100
 - 0s - loss: 0.3186 - accuracy: 0.9583 - val_loss: 0.3104 - val_accuracy: 0.9583

Epoch 00092: val_loss improved from 0.31307 to 0.31036, saving model to model/iris_deep.hdf5
Epoch 93/100
 - 0s - loss: 0.3167 - accuracy: 0.9583 - val_loss: 0.3064 - val_accuracy: 1.0000

Epoch 00093: val_loss improved from 0.31036 to 0.30643, saving model to model/iris_deep.hdf5
Epo

In [42]:
from keras.models import load_model
model_deep = load_model('model/iris_deep.hdf5')

In [45]:
model.evaluate(x_test, keras.utils.to_categorical(y_test))[1]

30/30 [==============================] - 0s 33us/step


0.9666666388511658

In [52]:
model_deep.predict_classes(test_data)[0]

2

In [46]:
model_deep.predict(test_data)

array([[0.00114793, 0.28892222, 0.7099299 ]], dtype=float32)

In [47]:
np.argmax(model_deep.predict(test_data)[0])

2